# Generated by Django 3.2.3 on 2021-05-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bits_commentaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='image',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
