# Generated by Django 3.2.3 on 2021-06-03 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listings_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='image',
        ),
    ]
